### Analysis of Football season and team stats

In [113]:
# load the csv file created after scraping the data from 'data' folder of the project
import pandas as pd

df = pd.read_csv(r'./data/df.csv')
df.head()

/Users/Sayli/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,B365>2.5,B365<2.5,P>2.5,P<2.5,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,AHh,B365AHH,B365AHA,PAHH,PAHA,MaxAHH,MaxAHA,AvgAHH,AvgAHA,B365CH,B365CD,B365CA,BWCH,BWCD,BWCA,IWCH,IWCD,IWCA,PSCH,PSCD,PSCA,WHCH,WHCD,WHCA,VCCH,VCCD,VCCA,MaxCH,MaxCD,MaxCA,AvgCH,AvgCD,AvgCA,B365C>2.5,B365C<2.5,PC>2.5,PC<2.5,MaxC>2.5,MaxC<2.5,AvgC>2.5,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,Bb1X2,BbMxH,BbAvH,BbMxD,BbAvD,BbMxA,BbAvA,BbOU,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,LBH,LBD,LBA,SJH,SJD,SJA,GBH,GBD,GBA,BSH,BSD,BSA,SBH,SBD,SBA,GB>2.5,GB<2.5,GBAHH,GBAHA,GBAH,LBAHH,LBAHA,LBAH,B365AH,SOH,SOD,SOA,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
0,E0,12/09/2020,12:30,Fulham,Arsenal,0.0,3.0,A,0.0,1.0,A,C Kavanagh,5.0,13.0,2.0,6.0,12.0,12.0,2.0,3.0,2.0,2.0,0.0,0.0,6.00,4.33,1.53,5.50,4.25,1.57,6.00,3.90,1.57,6.16,4.51,1.56,6.50,4.2,1.53,6.50,4.20,1.55,6.55,4.55,1.60,5.94,4.34,1.55,1.72,2.10,1.80,2.13,1.84,2.18,1.76,2.10,1.00,1.93,1.97,1.96,1.96,2.00,1.99,1.93,1.95,5.00,4.00,1.66,5.50,4.00,1.62,5.25,3.90,1.67,5.48,3.98,1.69,5.50,3.8,1.65,5.50,3.90,1.67,5.75,4.20,1.71,5.36,3.93,1.67,2.0,1.80,2.06,1.86,2.10,1.92,2.00,1.84,0.75,2.01,1.89,2.02,1.91,2.13,1.92,2.02,1.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,12/09/2020,15:00,Crystal Palace,Southampton,1.0,0.0,H,1.0,0.0,H,J Moss,5.0,9.0,3.0,5.0,14.0,11.0,7.0,3.0,2.0,1.0,0.0,0.0,3.10,3.25,2.37,3.00,3.20,2.45,3.15,2.95,2.40,3.32,3.29,2.40,3.20,3.2,2.35,3.20,3.20,2.40,3.36,3.36,2.50,3.18,3.22,2.39,2.20,1.66,2.34,1.68,2.36,1.73,2.24,1.67,0.25,1.85,2.05,1.88,2.05,1.88,2.07,1.84,2.03,3.00,3.25,2.40,3.00,3.30,2.40,3.05,2.90,2.45,3.09,3.27,2.54,3.10,3.1,2.45,3.10,3.25,2.45,3.25,3.33,2.55,3.08,3.22,2.47,2.2,1.66,2.26,1.72,2.27,1.78,2.18,1.70,0.25,1.78,2.13,1.79,2.17,1.85,2.18,1.79,2.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,12/09/2020,17:30,Liverpool,Leeds,4.0,3.0,H,3.0,2.0,H,M Oliver,22.0,6.0,6.0,3.0,9.0,6.0,9.0,0.0,1.0,0.0,0.0,0.0,1.28,6.00,9.50,1.26,6.25,10.50,1.35,5.00,8.50,1.31,6.25,9.92,1.27,6.0,10.00,1.30,5.75,10.50,1.35,6.50,10.75,1.30,5.96,9.68,1.53,2.50,1.56,2.60,1.56,2.68,1.52,2.53,-1.50,1.95,1.95,1.97,1.95,2.00,2.08,1.90,1.97,1.25,6.00,11.00,1.25,6.25,11.00,1.30,6.00,9.00,1.28,6.34,11.38,1.25,6.0,12.00,1.29,6.00,11.50,1.30,6.75,12.27,1.28,6.16,10.63,1.5,2.62,1.51,2.76,1.53,2.82,1.50,2.62,-1.50,1.85,2.05,1.85,2.08,1.90,2.16,1.84,2.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,12/09/2020,20:00,West Ham,Newcastle,0.0,2.0,A,0.0,0.0,D,S Attwell,15.0,15.0,3.0,2.0,13.0,7.0,8.0,7.0,2.0,2.0,0.0,0.0,2.15,3.40,3.40,2.15,3.40,3.40,2.15,3.15,3.40,2.18,3.61,3.50,2.15,3.5,3.40,2.15,3.40,3.60,2.24,3.70,3.60,2.15,3.48,3.42,1.90,1.90,2.00,1.91,2.05,1.95,1.97,1.86,-0.50,2.07,1.72,2.17,1.78,2.17,1.81,2.12,1.75,1.95,3.60,3.75,1.95,3.70,3.75,2.05,3.25,3.75,2.04,3.59,3.92,2.00,3.5,3.80,2.00,3.50,3.90,2.07,3.78,3.99,2.01,3.57,3.79,1.9,1.90,2.00,1.92,2.00,2.05,1.91,1.92,-0.50,2.03,1.87,2.04,1.88,2.09,1.91,2.02,1.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,13/09/2020,14:00,West Brom,Leicester,0.0,3.0,A,0.0,0.0,D,A Taylor,7.0,13.0,1.0,7.0,12.0,9.0,2.0,5.0,1.0,1.0,0.0,0.0,3.80,3.60,1.95,3.70,3.60,2.00,3.85,3.20,2.00,4.00,3.59,2.00,3.80,3.6,1.95,4.00,3.50,1.95,4.00,3.82,2.04,3.87,3.57,1.97,1.90,1.90,2.00,1.91,2.02,2.03,1.92,1.90,0.50,1.91,1.99,1.92,2.00,1.93,2.02,1.88,1.97,3.25,3.40,2.20,3.30,3.40,2.20,3.35,3.00,2.30,3.38,3.38,2.32,3.30,3.3,2.25,3.30,3.30,2.30,3.55,3.50,2.38,3.32,3.33,2.28,2.2,1.66,2.23,1.74,2.28,1.82,2.15,1.73,0.25,1.92,1.98,1.93,1.99,1.95,2.01,1.91,1.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [114]:
pd.options.display.max_columns = None

In [115]:
pd.options.display.max_rows = None

In [116]:
def change_into_datetime(col):
    df[col]=pd.to_datetime(df[col])
change_into_datetime("Date")
df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,B365>2.5,B365<2.5,P>2.5,P<2.5,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,AHh,B365AHH,B365AHA,PAHH,PAHA,MaxAHH,MaxAHA,AvgAHH,AvgAHA,B365CH,B365CD,B365CA,BWCH,BWCD,BWCA,IWCH,IWCD,IWCA,PSCH,PSCD,PSCA,WHCH,WHCD,WHCA,VCCH,VCCD,VCCA,MaxCH,MaxCD,MaxCA,AvgCH,AvgCD,AvgCA,B365C>2.5,B365C<2.5,PC>2.5,PC<2.5,MaxC>2.5,MaxC<2.5,AvgC>2.5,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,Bb1X2,BbMxH,BbAvH,BbMxD,BbAvD,BbMxA,BbAvA,BbOU,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,LBH,LBD,LBA,SJH,SJD,SJA,GBH,GBD,GBA,BSH,BSD,BSA,SBH,SBD,SBA,GB>2.5,GB<2.5,GBAHH,GBAHA,GBAH,LBAHH,LBAHA,LBAH,B365AH,SOH,SOD,SOA,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
0,E0,2020-12-09,12:30,Fulham,Arsenal,0.0,3.0,A,0.0,1.0,A,C Kavanagh,5.0,13.0,2.0,6.0,12.0,12.0,2.0,3.0,2.0,2.0,0.0,0.0,6.00,4.33,1.53,5.50,4.25,1.57,6.00,3.90,1.57,6.16,4.51,1.56,6.50,4.2,1.53,6.50,4.20,1.55,6.55,4.55,1.60,5.94,4.34,1.55,1.72,2.10,1.80,2.13,1.84,2.18,1.76,2.10,1.00,1.93,1.97,1.96,1.96,2.00,1.99,1.93,1.95,5.00,4.00,1.66,5.50,4.00,1.62,5.25,3.90,1.67,5.48,3.98,1.69,5.50,3.8,1.65,5.50,3.90,1.67,5.75,4.20,1.71,5.36,3.93,1.67,2.0,1.80,2.06,1.86,2.10,1.92,2.00,1.84,0.75,2.01,1.89,2.02,1.91,2.13,1.92,2.02,1.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,2020-12-09,15:00,Crystal Palace,Southampton,1.0,0.0,H,1.0,0.0,H,J Moss,5.0,9.0,3.0,5.0,14.0,11.0,7.0,3.0,2.0,1.0,0.0,0.0,3.10,3.25,2.37,3.00,3.20,2.45,3.15,2.95,2.40,3.32,3.29,2.40,3.20,3.2,2.35,3.20,3.20,2.40,3.36,3.36,2.50,3.18,3.22,2.39,2.20,1.66,2.34,1.68,2.36,1.73,2.24,1.67,0.25,1.85,2.05,1.88,2.05,1.88,2.07,1.84,2.03,3.00,3.25,2.40,3.00,3.30,2.40,3.05,2.90,2.45,3.09,3.27,2.54,3.10,3.1,2.45,3.10,3.25,2.45,3.25,3.33,2.55,3.08,3.22,2.47,2.2,1.66,2.26,1.72,2.27,1.78,2.18,1.70,0.25,1.78,2.13,1.79,2.17,1.85,2.18,1.79,2.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,2020-12-09,17:30,Liverpool,Leeds,4.0,3.0,H,3.0,2.0,H,M Oliver,22.0,6.0,6.0,3.0,9.0,6.0,9.0,0.0,1.0,0.0,0.0,0.0,1.28,6.00,9.50,1.26,6.25,10.50,1.35,5.00,8.50,1.31,6.25,9.92,1.27,6.0,10.00,1.30,5.75,10.50,1.35,6.50,10.75,1.30,5.96,9.68,1.53,2.50,1.56,2.60,1.56,2.68,1.52,2.53,-1.50,1.95,1.95,1.97,1.95,2.00,2.08,1.90,1.97,1.25,6.00,11.00,1.25,6.25,11.00,1.30,6.00,9.00,1.28,6.34,11.38,1.25,6.0,12.00,1.29,6.00,11.50,1.30,6.75,12.27,1.28,6.16,10.63,1.5,2.62,1.51,2.76,1.53,2.82,1.50,2.62,-1.50,1.85,2.05,1.85,2.08,1.90,2.16,1.84,2.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,2020-12-09,20:00,West Ham,Newcastle,0.0,2.0,A,0.0,0.0,D,S Attwell,15.0,15.0,3.0,2.0,13.0,7.0,8.0,7.0,2.0,2.0,0.0,0.0,2.15,3.40,3.40,2.15,3.40,3.40,2.15,3.15,3.40,2.18,3.61,3.50,2.15,3.5,3.40,2.15,3.40,3.60,2.24,3.70,3.60,2.15,3.48,3.42,1.90,1.90,2.00,1.91,2.05,1.95,1.97,1.86,-0.50,2.07,1.72,2.17,1.78,2.17,1.81,2.12,1.75,1.95,3.60,3.75,1.95,3.70,3.75,2.05,3.25,3.75,2.04,3.59,3.92,2.00,3.5,3.80,2.00,3.50,3.90,2.07,3.78,3.99,2.01,3.57,3.79,1.9,1.90,2.00,1.92,2.00,2.05,1.91,1.92,-0.50,2.03,1.87,2.04,1.88,2.09,1.91,2.02,1.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,2020-09-13,14:00,West Brom,Leicester,0.0,3.0,A,0.0,0.0,D,A Taylor,7.0,13.0,1.0,7.0,12.0,9.0,2.0,5.0,1.0,1.0,0.0,0.0,3.80,3.60,1.95,3.70,3.60,2.00,3.85,3.20,2.00,4.00,3.59,2.00,3.80,3.6,1.95,4.00,3.50,1.95,4.00,3.82,2.04,3.87,3.57,1.97,1.90,1.90,2.00,1.91,2.02,2.03,1.92,1.90,0.50,1.91,1.99,1.92,2.00,1.93,2.02,1.88,1.97,3.25,3.40,2.20,3.30,3.40,2.20,3.35,3.00,2.30,3.38,3.38,2.32,3.30,3.3,2.25,3.30,3.30,2.30,3.55,3.50,2.38,3.32,3.33,2.28,2.2,1.66,2.23,1.74,2.28,1.82,2.15,1.73,0.25,1.92,1.98,1.93,1.99,1.95,2.01,1.91,1.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [117]:
#removing betting data columns from original df
#removing 21-22 season as it is incomplete and not suitable for further analysis

df_complete = df.iloc[323: , :24] 
df_complete = df_complete.sort_index(ascending=False)

df_complete =df_complete.drop(['Div','Time'],axis=1)
df_complete.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
7130,2003-11-05,West Brom,Newcastle,2.0,2.0,D,0.0,1.0,A,G Barber,8.0,14.0,3.0,9.0,9.0,8.0,2.0,8.0,0.0,0.0,0.0,0.0
7129,2003-11-05,Tottenham,Blackburn,0.0,4.0,A,0.0,2.0,A,A D'Urso,11.0,13.0,7.0,9.0,9.0,12.0,6.0,3.0,1.0,1.0,1.0,0.0
7128,2003-11-05,Sunderland,Arsenal,0.0,4.0,A,0.0,2.0,A,P Durkin,7.0,20.0,3.0,13.0,16.0,12.0,6.0,10.0,1.0,0.0,0.0,0.0
7127,2003-11-05,Man City,Southampton,0.0,1.0,A,0.0,1.0,A,M Dean,17.0,6.0,7.0,3.0,14.0,14.0,10.0,4.0,3.0,4.0,0.0,0.0
7126,2003-11-05,Leeds,Aston Villa,3.0,1.0,H,1.0,1.0,D,M Halsey,11.0,18.0,5.0,6.0,18.0,14.0,1.0,8.0,0.0,1.0,0.0,0.0

In [118]:
df_complete = df_complete.dropna()
# df_complete.isnull().sum()

Drop irrelevant columns and rename other columns to understand the contents from column title

In [119]:
df_complete.columns = ['Date','HomeTeam','AwayTeam','H_Goals','A_Goals','FT_Result','H_HT_Goals','A_HT_Goals',
                        'HT_Result','Referee','H_Shots','A_Shots','H_Shots_Target','A_Shots_Target','H_Foul',
                        'A_Foul','H_Corner','A_Corner','H_Yellow','A_Yellow','H_Red','A_Red']

df_complete.head()

,Date,HomeTeam,AwayTeam,H_Goals,A_Goals,FT_Result,H_HT_Goals,A_HT_Goals,HT_Result,Referee,H_Shots,A_Shots,H_Shots_Target,A_Shots_Target,H_Foul,A_Foul,H_Corner,A_Corner,H_Yellow,A_Yellow,H_Red,A_Red
7130,2003-11-05,West Brom,Newcastle,2.0,2.0,D,0.0,1.0,A,G Barber,8.0,14.0,3.0,9.0,9.0,8.0,2.0,8.0,0.0,0.0,0.0,0.0
7129,2003-11-05,Tottenham,Blackburn,0.0,4.0,A,0.0,2.0,A,A D'Urso,11.0,13.0,7.0,9.0,9.0,12.0,6.0,3.0,1.0,1.0,1.0,0.0
7128,2003-11-05,Sunderland,Arsenal,0.0,4.0,A,0.0,2.0,A,P Durkin,7.0,20.0,3.0,13.0,16.0,12.0,6.0,10.0,1.0,0.0,0.0,0.0
7127,2003-11-05,Man City,Southampton,0.0,1.0,A,0.0,1.0,A,M Dean,17.0,6.0,7.0,3.0,14.0,14.0,10.0,4.0,3.0,4.0,0.0,0.0
7126,2003-11-05,Leeds,Aston Villa,3.0,1.0,H,1.0,1.0,D,M Halsey,11.0,18.0,5.0,6.0,18.0,14.0,1.0,8.0,0.0,1.0,0.0,0.0

In [120]:
#sorting data according to the Date

df_analysis = df_complete.sort_values(['Date']).reset_index(drop=True)
df_analysis.head()

,Date,HomeTeam,AwayTeam,H_Goals,A_Goals,FT_Result,H_HT_Goals,A_HT_Goals,HT_Result,Referee,H_Shots,A_Shots,H_Shots_Target,A_Shots_Target,H_Foul,A_Foul,H_Corner,A_Corner,H_Yellow,A_Yellow,H_Red,A_Red
0,2002-01-09,Chelsea,Arsenal,1.0,1.0,D,1.0,0.0,H,A D'Urso,8.0,8.0,2.0,5.0,20.0,16.0,6.0,2.0,5.0,2.0,0.0,1.0
1,2002-01-09,Bolton,Aston Villa,1.0,0.0,H,0.0,0.0,D,S Dunn,13.0,12.0,6.0,5.0,9.0,11.0,4.0,5.0,2.0,3.0,0.0,0.0
2,2002-01-12,Newcastle,Everton,2.0,1.0,H,0.0,1.0,A,M Halsey,24.0,7.0,15.0,5.0,13.0,18.0,11.0,2.0,0.0,1.0,0.0,1.0
3,2002-01-12,Liverpool,Man United,1.0,2.0,A,0.0,0.0,D,A Wiley,13.0,5.0,7.0,4.0,13.0,11.0,5.0,2.0,1.0,4.0,0.0,0.0
4,2002-01-12,Leeds,Charlton,1.0,2.0,A,1.0,0.0,H,A D'Urso,18.0,14.0,6.0,10.0,14.0,15.0,5.0,11.0,1.0,1.0,0.0,0.0

Each EPL season has 380 games.
So we can make a new column called season which changes after every 380 games.

In [121]:
season_start=2
season_end=3
season_list = []

for x in range (18):
    for y in range (380):
        season_list.append((str(season_start)+'-'+str(season_end)))
    season_start = season_start + 1
    season_end = season_end + 1

# season_list

In the above step, we made an empty list and added the seasons into it changing every 380 games.
We will convert this list into a pandas dataframe and later concatenate this data frame with the df_analysis.

In [122]:
season_df = pd.DataFrame({'Season':season_list})

data_by_seasons = pd.concat([season_df,df_analysis], axis=1)
data_by_seasons.head()

,Season,Date,HomeTeam,AwayTeam,H_Goals,A_Goals,FT_Result,H_HT_Goals,A_HT_Goals,HT_Result,Referee,H_Shots,A_Shots,H_Shots_Target,A_Shots_Target,H_Foul,A_Foul,H_Corner,A_Corner,H_Yellow,A_Yellow,H_Red,A_Red
0,2-3,2002-01-09,Chelsea,Arsenal,1.0,1.0,D,1.0,0.0,H,A D'Urso,8.0,8.0,2.0,5.0,20.0,16.0,6.0,2.0,5.0,2.0,0.0,1.0
1,2-3,2002-01-09,Bolton,Aston Villa,1.0,0.0,H,0.0,0.0,D,S Dunn,13.0,12.0,6.0,5.0,9.0,11.0,4.0,5.0,2.0,3.0,0.0,0.0
2,2-3,2002-01-12,Newcastle,Everton,2.0,1.0,H,0.0,1.0,A,M Halsey,24.0,7.0,15.0,5.0,13.0,18.0,11.0,2.0,0.0,1.0,0.0,1.0
3,2-3,2002-01-12,Liverpool,Man United,1.0,2.0,A,0.0,0.0,D,A Wiley,13.0,5.0,7.0,4.0,13.0,11.0,5.0,2.0,1.0,4.0,0.0,0.0
4,2-3,2002-01-12,Leeds,Charlton,1.0,2.0,A,1.0,0.0,H,A D'Urso,18.0,14.0,6.0,10.0,14.0,15.0,5.0,11.0,1.0,1.0,0.0,0.0

In [123]:
data_by_seasons = data_by_seasons.dropna()
data_by_seasons.head()

,Season,Date,HomeTeam,AwayTeam,H_Goals,A_Goals,FT_Result,H_HT_Goals,A_HT_Goals,HT_Result,Referee,H_Shots,A_Shots,H_Shots_Target,A_Shots_Target,H_Foul,A_Foul,H_Corner,A_Corner,H_Yellow,A_Yellow,H_Red,A_Red
0,2-3,2002-01-09,Chelsea,Arsenal,1.0,1.0,D,1.0,0.0,H,A D'Urso,8.0,8.0,2.0,5.0,20.0,16.0,6.0,2.0,5.0,2.0,0.0,1.0
1,2-3,2002-01-09,Bolton,Aston Villa,1.0,0.0,H,0.0,0.0,D,S Dunn,13.0,12.0,6.0,5.0,9.0,11.0,4.0,5.0,2.0,3.0,0.0,0.0
2,2-3,2002-01-12,Newcastle,Everton,2.0,1.0,H,0.0,1.0,A,M Halsey,24.0,7.0,15.0,5.0,13.0,18.0,11.0,2.0,0.0,1.0,0.0,1.0
3,2-3,2002-01-12,Liverpool,Man United,1.0,2.0,A,0.0,0.0,D,A Wiley,13.0,5.0,7.0,4.0,13.0,11.0,5.0,2.0,1.0,4.0,0.0,0.0
4,2-3,2002-01-12,Leeds,Charlton,1.0,2.0,A,1.0,0.0,H,A D'Urso,18.0,14.0,6.0,10.0,14.0,15.0,5.0,11.0,1.0,1.0,0.0,0.0

We need to stack HomeTeam and AwayTeam into one column called Team - to get season & team wise data

In [124]:
delta_names = ['Goals','HT_Goals','Shots_Target','Foul','Corner','Yellow','Red']

for column in delta_names:
    h_delta_column = 'H_Delta_'+ column
    a_delta_column = 'A_Delta_'+ column
    
    h_column = 'H_'+ column
    a_column = 'A_'+ column

    data_by_seasons[h_delta_column] = data_by_seasons[h_column]-data_by_seasons[a_column]
    data_by_seasons[a_delta_column] = data_by_seasons[a_column]-data_by_seasons[h_column]
    
column_names = ['Delta_Goals','Delta_HT_Goals','Delta_Shots_Target','Delta_Foul','Delta_Corner','Delta_Yellow','Delta_Red']

h_column_names = ['Season','HomeTeam','H_Goals','A_Goals','FT_Result','H_HT_Goals','A_HT_Goals','HT_Result','H_Shots_Target','A_Shots_Target','H_Foul','A_Foul','H_Corner','A_Corner','H_Yellow','A_Yellow','H_Red','A_Red']

a_column_names = ['Season','AwayTeam','A_Goals','H_Goals','FT_Result','A_HT_Goals','A_HT_Goals','HT_Result','A_Shots_Target','H_Shots_Target','A_Foul','H_Foul','A_Corner','H_Corner','A_Yellow','H_Yellow','A_Red','H_Red']


column_names_new = ['Season','Team','Goals','Goals_Received','FT_Result','HT_Goals','HT_Goals_Received','HT_Result','Shots_Target','Shots_Target_Received','Fouls','Got_Fouled','Corner','Corner_Received','Yellow','Yellow_Received','Red','Red_Received','Delta_Goals','Delta_HT_Goals','Delta_Shots_On_Target','Delta_Foul','Delta_Corner','Delta_Yellow','Delta_Red']

for column in column_names: 
    h_column_names.append("H_" + column)
    a_column_names.append("A_" + column)

In [134]:
df_home = data_by_seasons.filter(h_column_names)
df_away = data_by_seasons.filter(a_column_names)

df_home.columns = column_names_new
df_away.columns = column_names_new

# df_total = df_home.append(df_away, ignore_index=True).sort_values(['Season','FT_Result', 'HT_Result'], ascending=[True,True, True])

# df_total_sorted = df_total['Season','Team','Goals','Goals_Received','Delta_Goals','FT_Result','HT_Goals','HT_Goals_Received','Delta_HT_Goals','HT_Result','Shots_On_Target','Shots_On_Target_Received','Delta_Shots_On_Target','Fouls','Got_Fouled','Delta_Fouls','Corners','Corners_Received','Delta_Corners','Yellow','Yellow_Received','Delta_Yellow','Red','Red_Received','Delta_Red']

df_total = df_home.append(df_away)
df_total.head()

,Season,Team,Goals,Goals_Received,FT_Result,HT_Goals,HT_Goals_Received,HT_Result,Shots_Target,Shots_Target_Received,Fouls,Got_Fouled,Corner,Corner_Received,Yellow,Yellow_Received,Red,Red_Received,Delta_Goals,Delta_HT_Goals,Delta_Shots_On_Target,Delta_Foul,Delta_Corner,Delta_Yellow,Delta_Red
0,2-3,Chelsea,1.0,1.0,D,1.0,0.0,H,2.0,5.0,20.0,16.0,6.0,2.0,5.0,2.0,0.0,1.0,0.0,1.0,-3.0,4.0,4.0,3.0,-1.0
1,2-3,Bolton,1.0,0.0,H,0.0,0.0,D,6.0,5.0,9.0,11.0,4.0,5.0,2.0,3.0,0.0,0.0,1.0,0.0,1.0,-2.0,-1.0,-1.0,0.0
2,2-3,Newcastle,2.0,1.0,H,0.0,1.0,A,15.0,5.0,13.0,18.0,11.0,2.0,0.0,1.0,0.0,1.0,1.0,-1.0,10.0,-5.0,9.0,-1.0,-1.0
3,2-3,Liverpool,1.0,2.0,A,0.0,0.0,D,7.0,4.0,13.0,11.0,5.0,2.0,1.0,4.0,0.0,0.0,-1.0,0.0,3.0,2.0,3.0,-3.0,0.0
4,2-3,Leeds,1.0,2.0,A,1.0,0.0,H,6.0,10.0,14.0,15.0,5.0,11.0,1.0,1.0,0.0,0.0,-1.0,1.0,-4.0,-1.0,-6.0,0.0,0.0

In [136]:
df_total.to_csv(r'./data/df_total.csv')